<a href="https://colab.research.google.com/github/MarinaChau/IASD_classes/blob/master/OML/ProjectOML_MarinaCHAU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Second-order optimization methods

In [2]:
# Preamble: useful toolboxes, librairies, functions, etc.

# Display
%matplotlib inline
import matplotlib.pyplot as plt

from math import sqrt # Square root

# NumPy - Matrix and vector structures
import numpy as np # NumPy library
from numpy.random import multivariate_normal, randn, uniform # Probability distributions

# SciPy - Efficient mathematical calculation
from scipy.linalg import norm # Euclidean norm
from scipy.linalg.special_matrices import toeplitz # Toeplitz matrices
from scipy.linalg import svdvals # Singular value decomposition
from scipy.optimize import check_grad # Check derivatives
from scipy.optimize import fmin_l_bfgs_b # Efficient method for minimization

## 1.1 Newton's method

### Implementation 1.1

In [103]:
def newton_method(w0, function_f, gradient_f, hessian_f, n_iter, eps = 0.0001):
    """
        A code for  Newton's method in its basic form

        Inputs:
            w0: Initial vector
            function_f: Objective function
            gradient_f: Gradient of the objective function
            hessian_f: hessian matrix of the objective function
            n_iter: Number of iterations
            eps: convergence stop

        Outputs:
            w_output: Final iterate of the method
    """

        ############
    # Initialize iteration counter
    k=1
    ####################
    # Main loop
    w = w0 - np.dot(np.linalg.inv(hessian_f(w0)), gradient_f(w0))
    while (np.linalg.norm(grad_f(w), 2) > eps and k < n_iter):
        
        # Select the stepsize and perform the update
        w = w - np.dot(np.linalg.inv(hessian_f(w)), gradient_f(w))
        
        # Increment the iteration count
        k += 1
        
    
    # End main loop
    ######################
    # Output
    print(w)
    w_output = w.copy()
    return w_output, k

def newton(w_0, grad_f, hess_f, n_max = 1000, eps = 0.0001):#Here f is useless
    n = 1
    w_k = w_0 - np.dot(np.linalg.inv(hess_f(w_0)), grad_f(w_0))
    while np.linalg.norm(grad_f(w_k), 2) > eps and n < n_max:
        w_k = w_k - np.dot(np.linalg.inv(hess_f(w_k)), grad_f(w_k))
        n+=1
    return w_k, n

### Question 1.1 

a) 

minimize  $  w∈R^3 q(w) := 2(w1 + w2 + w3 − 3)^2 + (w1 − w2)^2 + (w2 − w3)^2 $

We have: $\nabla f (w) = 
\begin{bmatrix}
          6w_1 + 2w_2 + 4w_3 -12 \\
          2w_1 + 8w_2 + 2w_3 -12\\     
          4w_1 + 2w_2 + 6w_3 -12
\end{bmatrix}$
and the hessian $\nabla^2f(w) = \begin{bmatrix}
          6 & 2 & 4\\
          2 & 8 & 2\\
          4 & 2 & 6
\end{bmatrix}$

After inverting the hessian:
$\nabla^2f(w)^{-1} = \begin{bmatrix}
          \frac{11}{36} & -\frac{1}{36} & -\frac{7}{36}\\
          -\frac{1}{36} & \frac{5}{36} & -\frac{1}{36}\\
          -\frac{7}{36} & -\frac{1}{36} & \frac{11}{36}
\end{bmatrix}$

So at step 1: with $ w_0 = \begin{bmatrix}
          0\\
          0\\
          0
\end{bmatrix}$

We get,

$w_1 = w_0 − [\nabla^2 f (w_0)]^{-1} \nabla f (w_0) = -\begin{bmatrix}
          \frac{11}{36} & -\frac{1}{36} & -\frac{7}{36}\\
          -\frac{1}{36} & \frac{5}{36} & -\frac{1}{36}\\
          -\frac{7}{36} & -\frac{1}{36} & \frac{11}{36}
\end{bmatrix}  \begin{bmatrix}
           -12 \\
           -12\\     
           -12
\end{bmatrix}$ =$\begin{bmatrix}
           1 \\
           1 \\     
           1
\end{bmatrix}$


Thus, after one iteration, it converges to the solution with Newton's method. 



b)

In [89]:
# Compute objective function f
def function(w_k):
    return 2*(w_k[0] + w_k[1] + w_k[2] -3)**2 + (w_k[0] - w_k[1])**2 + (w_k[1]- w_k[2])**2


# Compute gradient_f
def grad_f(w_k):
    gradient_f = np.array([6* w_k[0] + 2 * w_k[1] + 4 * w_k[2] - 12,
                           2 * w_k[0] + 8 * w_k[1] + 2 * w_k[2] -12,
                           4 * w_k[0] + 2 * w_k[1] + 6 * w_k[2] - 12])
    return gradient_f

# Compute hessian_f
def hess_f(w):
    return np.array(([6,2,4],[2,8,2], [4, 2,6]))





In [106]:
# Different starting points
w_origin = np.array([0, 0, 0])
w_1 = np.array([1, 1, 1])
w_2 = np.array([1, 0, 0])
n_iter= 1000

In [107]:
w_origin_star, n_iter_origin = newton_method(w_origin, function, grad_f, hess_f, n_iter)
print(f"With starting point {w_origin} it has converged in {n_iter_origin} steps.")



[1. 1. 1.]
With starting point [0 0 0] it has converged in 1 steps.


In [108]:
w_1_star, n_iter_1 = newton_method(w_1,  function, grad_f, hess_f, n_iter)
print(f"With starting point {w_1} it has converged in {n_iter_1} steps.")

[1. 1. 1.]
With starting point [1 1 1] it has converged in 1 steps.


In [109]:
w_2_star, n_iter_2 = newton_method(w_2,  function, grad_f, hess_f, n_iter)
print(f"With starting point {w_2} it has converged in {n_iter_2} steps.")

[1. 1. 1.]
With starting point [1 0 0] it has converged in 1 steps.


We can observe convergence in one iteration for other starting points.



### Question 1.2